version: '3'

services:

  cs-flash-cards:
    build: .
    environment:
      - USERNAME=${USERNAME-admin}
      - PASSWORD=${PASSWORD-default}
      - SECRET_KEY=${SECRET_KEY-your-secure-secret-key-here}
    volumes:
      - ./cards-empty.db:/src/db/cards.db
      - ./cards-jwasham-extreme.db:/src/db/cards.db
      - ./cards-jwasham.db:/src/db/cards.db
